In [84]:
import glob
import pandas as pd
import re

In [85]:

df_medqa = pd.read_json('./resources/data/medqa.jsonl', lines=True)
letter_to_number = {'A': 1, 'B': 2, 'C': 3, 'D': 4, 'E': 5}
real_ans = df_medqa["answer_idx"].apply(lambda x: letter_to_number.get(x))
df_medqa

,question,answer,options,meta_info,answer_idx
0,A junior orthopaedic surgery resident is compl...,Tell the attending that he cannot fail to disc...,{'A': 'Disclose the error to the patient but l...,step1,C
1,A 67-year-old man with transitional cell carci...,Cross-linking of DNA,"{'A': 'Inhibition of thymidine synthesis', 'B'...",step1,E
2,Two weeks after undergoing an emergency cardia...,Cholesterol embolization,"{'A': 'Renal papillary necrosis', 'B': 'Allerg...",step2&3,C
3,A 39-year-old woman is brought to the emergenc...,"Lactose-fermenting, gram-negative rods forming...","{'A': 'Coagulase-positive, gram-positive cocci...",step1,D
4,A 35-year-old man comes to the physician becau...,Ketotifen eye drops,"{'A': 'Erythromycin ointment', 'B': 'Ketotifen...",step2&3,B
...,...,...,...,...,...
1268,A 39-year-old woman presents to the clinic for...,Thyroid-stimulating hormone (TSH),"{'A': 'Erythropoietin', 'B': 'Glucose', 'C': '...",step2&3,E
1269,A 38-year-old woman comes to the physician bec...,Medication abuse,"{'A': 'Celiac disease', 'B': 'Carcinoid tumor'...",step2&3,E
1270,A 21-year-old college student comes to the phy...,Stop evening exercise,"{'A': 'Trial of diphenhydramine', 'B': 'Comple...",step2&3,C
1271,A 19-year-old man is brought to the physician ...,Schizotypal personality disorder,"{'A': 'Social anxiety disorder', 'B': 'Avoidan...",step2&3,C
1272,A 79-year-old man presents to the office due t...,Chronic obstructive pulmonary disease (COPD),"{'A': 'Asthma', 'B': 'Lymphangioleiomyomatosis...",step1,C

In [87]:
df_list = []
resp = []

def extract_number(filename):
    match = re.search(r'(\d+).csv', filename)
    return int(match.group(1)) if match else 0

for file in sorted(glob.glob("resources/medqa/gpt4omini-medqa-vote/*.csv"), key=extract_number):
    df = pd.read_csv(file).head(1)
    resp.append(df)


pred_ans = [int(df.answer.mode()[0]) for df in resp]
print(sum(real_ans == pred_ans) / len(real_ans))
print(sum(real_ans == pred_ans))

0.7297721916732128
929

In [68]:
df_list = []
resp = []

def extract_number(filename):
    match = re.search(r'(\d+).csv', filename)
    return int(match.group(1)) if match else 0

for file in sorted(glob.glob("resources/medqa/gpt4omini-medqa-vote/*.csv"), key=extract_number):
    df = pd.read_csv(file)
    resp.append(df)


pred_ans = [int(df.answer.mode()[0]) for df in resp]
print(sum(real_ans == pred_ans) / len(real_ans))
print(sum(real_ans == pred_ans))

df_list.append(
    pd.DataFrame(
        {
            "model": "vote",
            "dataset": "MedQA",
            "acc": sum(real_ans == pred_ans) / len(real_ans),
            "n_samples": len(real_ans),
            "prob_id": range(len(real_ans)),
            "pred_ans": pred_ans,
            "real_ans": real_ans.tolist(),
        }
    )
)

0.7415553809897879
944

In [69]:

resp = []

def extract_number(filename):
    match = re.search(r'(\d+).csv', filename)
    return int(match.group(1)) if match else 0

for file in sorted(glob.glob("resources/medqa/gpt4omini-medqa-bayesian/*.csv"), key=extract_number):
    df = pd.read_csv(file)
    resp.append(df)


pred_ans = [int(df.answer.mode()[0]) for df in resp]
sum(real_ans == pred_ans) / len(real_ans)

df_list.append(
    pd.DataFrame(
        {
            "model": "bayesian",
            "dataset": "MedQA",
            "acc": sum(real_ans == pred_ans) / len(real_ans),
            "n_samples": len(real_ans),
            "prob_id": range(len(real_ans)),
            "pred_ans": pred_ans,
            "real_ans": real_ans.tolist(),
        }
    )
)

In [70]:

resp = []

def extract_number(filename):
    match = re.search(r'(\d+).csv', filename)
    return int(match.group(1)) if match else 0

for file in sorted(glob.glob("resources/medqa/gpt4omini-medqa-sprt-0510050947/*.csv"), key=extract_number):
    df = pd.read_csv(file)
    resp.append(df)



pred_ans = [int(df.answer.mode()[0]) for df in resp]
sum(real_ans == pred_ans) / len(real_ans)

df_list.append(
    pd.DataFrame(
        {
            "model": "sprt",
            "dataset": "MedQA",
            "acc": sum(real_ans == pred_ans) / len(real_ans),
            "n_samples": len(real_ans),
            "prob_id": range(len(real_ans)),
            "pred_ans": pred_ans,
            "real_ans": real_ans.tolist(),
        }
    )
)

In [71]:

resp = []

def extract_number(filename):
    match = re.search(r'(\d+).csv', filename)
    return int(match.group(1)) if match else 0

for file in sorted(glob.glob("resources/medqa/gpt4omini-medqa-msprt-25600509446/*.csv"), key=extract_number):
    df = pd.read_csv(file)
    resp.append(df)



pred_ans = [int(df.answer.mode()[0]) for df in resp]
sum(real_ans == pred_ans) / len(real_ans)

df_list.append(
    pd.DataFrame(
        {
            "model": "msprt",
            "dataset": "MedQA",
            "acc": sum(real_ans == pred_ans) / len(real_ans),
            "n_samples": len(real_ans),
            "prob_id": range(len(real_ans)),
            "pred_ans": pred_ans,
            "real_ans": real_ans.tolist(),
        }
    )
)

In [72]:
df_result = pd.concat(df_list)

In [73]:
df_result

      model dataset       acc  n_samples  prob_id  pred_ans  real_ans
0      vote   MedQA  0.741555       1273        0         2         3
1      vote   MedQA  0.741555       1273        1         5         5
2      vote   MedQA  0.741555       1273        2         3         3
3      vote   MedQA  0.741555       1273        3         2         4
4      vote   MedQA  0.741555       1273        4         2         2
...     ...     ...       ...        ...      ...       ...       ...
1268  msprt   MedQA  0.738413       1273     1268         5         5
1269  msprt   MedQA  0.738413       1273     1269         3         5
1270  msprt   MedQA  0.738413       1273     1270         2         3
1271  msprt   MedQA  0.738413       1273     1271         3         3
1272  msprt   MedQA  0.738413       1273     1272         3         3

[5092 rows x 7 columns]

In [75]:
df_result.loc[df_result.pred_ans != df_result.real_ans,:]

      model dataset       acc  n_samples  prob_id  pred_ans  real_ans
0      vote   MedQA  0.741555       1273        0         2         3
3      vote   MedQA  0.741555       1273        3         2         4
5      vote   MedQA  0.741555       1273        5         3         5
6      vote   MedQA  0.741555       1273        6         2         4
13     vote   MedQA  0.741555       1273       13         2         5
...     ...     ...       ...        ...      ...       ...       ...
1260  msprt   MedQA  0.738413       1273     1260         2         3
1262  msprt   MedQA  0.738413       1273     1262         1         3
1265  msprt   MedQA  0.738413       1273     1265         3         2
1269  msprt   MedQA  0.738413       1273     1269         3         5
1270  msprt   MedQA  0.738413       1273     1270         2         3

[1326 rows x 7 columns]

In [76]:
wrong_answer_count = df_result.loc[df_result.pred_ans != df_result.real_ans,["prob_id"]].value_counts()
wrong_answer_list = sorted([x[0] for x in wrong_answer_count.index.values[wrong_answer_count == 4].tolist()])
len(wrong_answer_list)

287

In [77]:
df_hard = df_medqa.iloc[wrong_answer_list,:]
df_hard.index = wrong_answer_list
df_hard

,question,answer,options,meta_info,answer_idx
0,A junior orthopaedic surgery resident is compl...,Tell the attending that he cannot fail to disc...,{'A': 'Disclose the error to the patient but l...,step1,C
3,A 39-year-old woman is brought to the emergenc...,"Lactose-fermenting, gram-negative rods forming...","{'A': 'Coagulase-positive, gram-positive cocci...",step1,D
5,A 39-year-old man presents to the emergency de...,Reassurance and continuous monitoring,"{'A': 'Diltiazem', 'B': 'Labetalol', 'C': 'Nit...",step2&3,E
6,A 68-year-old male comes to the physician for ...,Common iliac artery aneurysm,"{'A': 'Renal artery stenosis', 'B': 'Benign pr...",step1,D
19,A 46-year-old man is brought to the emergency ...,"Benzodiazepine intoxication\n""","{'A': 'Hypoglycemia', 'B': 'Cerebral ischemia'...",step2&3,E
...,...,...,...,...,...
1260,A 51-year-old man is brought to the physician ...,Direct activation of dopamine receptors,{'A': 'Peripheral inhibition of DOPA decarboxy...,step1,C
1262,A 30-year-old man presents to the emergency ro...,Blocking antibody attack on the O antigen,{'A': 'ADP ribosylation of elongation factor 2...,step1,C
1265,A 74-year-old woman with a history of hyperten...,Delirium,"{'A': 'Alzheimer dementia', 'B': 'Delirium', '...",step1,B
1269,A 38-year-old woman comes to the physician bec...,Medication abuse,"{'A': 'Celiac disease', 'B': 'Carcinoid tumor'...",step2&3,E
1270,A 21-year-old college student comes to the phy...,Stop evening exercise,"{'A': 'Trial of diphenhydramine', 'B': 'Comple...",step2&3,C

In [88]:
example = df_hard.loc[5,:]

print(example.question)

A 39-year-old man presents to the emergency department because of progressively worsening chest pain and nausea that started at a local bar 30 minutes prior. The pain radiates to the epigastric area. He has a 5-year history of untreated hypertension. He has smoked 1 pack of cigarettes daily for the past 5 years and started abusing cocaine 2 weeks before his emergency room visit. The patient is diaphoretic and in marked distress. What should be the first step in management?

In [89]:
print(example.answer)

Reassurance and continuous monitoring

In [90]:
print(example.options)

{'A': 'Diltiazem', 'B': 'Labetalol', 'C': 'Nitroglycerin', 'D': 'Propranolol', 'E': 'Reassurance and continuous monitoring'}

In [103]:
letter_to_number = {'A': 1, 'B': 2, 'C': 3, 'D': 4, 'E': 5}

sorted_keys = list("ABCDE")
formatted_options = ['\\n'.join([str(i+1)+". " +x[key] for i, key in enumerate(sorted_keys)]) for x in df_hard['options']]

instruction_text = 'Please select the number between 1 and 5 that corresponds to the correct answer.'

formatted_question = [f'{q}\\n\\n{instruction_text}\\n\\n{o}' for q,o in zip(df_hard['question'], formatted_options)]

answer_number = df_hard["answer_idx"].apply(lambda x: letter_to_number.get(x))

if answer_number is None:
    raise ValueError("The answer index does not match any known option.")

df_hard = pd.DataFrame({
    "input": formatted_question,
    "target": answer_number
})
df_hard

                                                  input  target
0     A junior orthopaedic surgery resident is compl...       3
3     A 39-year-old woman is brought to the emergenc...       4
5     A 39-year-old man presents to the emergency de...       5
6     A 68-year-old male comes to the physician for ...       4
19    A 46-year-old man is brought to the emergency ...       5
...                                                 ...     ...
1260  A 51-year-old man is brought to the physician ...       3
1262  A 30-year-old man presents to the emergency ro...       3
1265  A 74-year-old woman with a history of hyperten...       2
1269  A 38-year-old woman comes to the physician bec...       5
1270  A 21-year-old college student comes to the phy...       3

[287 rows x 2 columns]

In [ ]:
df_hard.to_json("./resources/data/medqa_hard.json", index=False)

In [ ]:
real_ans_hard = df_hard.target.values

df_list = []
resp = []

def extract_number(filename):
    match = re.search(r'(\d+).csv', filename)
    return int(match.group(1)) if match else 0

for file in sorted(glob.glob("./published/medqa_hard_vote_5/*.csv"), key=extract_number):
    df = pd.read_csv(file).head(1)
    resp.append(df)


pred_ans = [int(df.answer.mode()[0]) for df in resp]
sum(real_ans_hard == pred_ans) / len(real_ans_hard)

0.6515679442508711

In [107]:
sum(real_ans_hard == pred_ans)

187

In [129]:
real_ans_hard = df_hard.target.values

df_list = []
resp = []

def extract_number(filename):
    match = re.search(r'(\d+).csv', filename)
    return int(match.group(1)) if match else 0

for file in sorted(glob.glob("published/medqa_hard_vote_5/*.csv"), key=extract_number):
    df = pd.read_csv(file)
    resp.append(df)


pred_ans = [int(df.answer.mode()[0]) for df in resp]
sum(real_ans_hard == pred_ans) / len(real_ans_hard)
print(len(real_ans_hard), sum(real_ans_hard == pred_ans))

287 191

In [113]:
idx = [ i for i, c in enumerate(real_ans_hard == pred_ans) if c == False]

In [125]:
count = 0
can_be_improved = 0
for i in idx:
    if len(resp[i].answer.value_counts()) == 1:
        continue
    print(i)
    print(resp[i].answer.value_counts())

    if real_ans_hard[i] in resp[i].answer:
        can_be_improved += 1
    count += 1

1
answer
2.0    4
4.0    1
Name: count, dtype: int64
30
answer
5.0    3
4.0    2
Name: count, dtype: int64
33
answer
1.0    3
3.0    2
Name: count, dtype: int64
60
answer
1.0    4
4.0    1
Name: count, dtype: int64
73
answer
5.0    4
4.0    1
Name: count, dtype: int64
90
answer
4.0    4
3.0    1
Name: count, dtype: int64
95
answer
2.0    4
1.0    1
Name: count, dtype: int64
115
answer
1.0    4
4.0    1
Name: count, dtype: int64
126
answer
1.0    3
3.0    2
Name: count, dtype: int64
131
answer
2.0    4
1.0    1
Name: count, dtype: int64
135
answer
3.0    4
4.0    1
Name: count, dtype: int64
145
answer
5.0    4
4.0    1
Name: count, dtype: int64
147
answer
2.0    4
1.0    1
Name: count, dtype: int64
153
answer
1.0    4
3.0    1
Name: count, dtype: int64
154
answer
4.0    3
3.0    1
2.0    1
Name: count, dtype: int64
159
answer
3.0    3
5.0    2
Name: count, dtype: int64
175
answer
5.0    3
4.0    2
Name: count, dtype: int64
180
answer
4.0    4
3.0    1
Name: count, dtype: int64
181
answer
3.0    4
1.0    1
Name: count, dtype: int64
189
answer
4.0    3
2.0    2
Name: count, dtype: int64
193
answer
2.0    4
4.0    1
Name: count, dtype: int64
198
answer
2.0    3
5.0    1
3.0    1
Name: count, dtype: int64
210
answer
5.0    3
1.0    2
Name: count, dtype: int64
213
answer
3.0    3
4.0    2
Name: count, dtype: int64
214
answer
2.0    3
1.0    2
Name: count, dtype: int64
216
answer
2.0    4
4.0    1
Name: count, dtype: int64
217
answer
2.0    4
1.0    1
Name: count, dtype: int64
218
answer
20.0    3
4.0     1
5.0     1
Name: count, dtype: int64
221
answer
1.0    3
3.0    2
Name: count, dtype: int64
225
answer
5.0    4
1.0    1
Name: count, dtype: int64
226
answer
3.0    4
1.0    1
Name: count, dtype: int64
238
answer
5.0    4
1.0    1
Name: count, dtype: int64
239
answer
5.0    4
2.0    1
Name: count, dtype: int64
252
answer
2.0    3
5.0    2
Name: count, dtype: int64
254
answer
3.0    3
2.0    2
Name: count, dtype: int64
262
answer
3.0    3
2.0    2
Name: count, dtype: int64
279
answer
1.0      2
480.0    2
2.0      1
Name: count, dtype: int64
284
answer
4.0    3
3.0    2
Name: count, dtype: int64
286
answer
5.0    4
2.0    1
Name: count, dtype: int64

In [128]:
print(len(idx), count, can_be_improved)

96 39 34